// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gubvtfwbcjogospapomc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1YnZ0ZndiY2pvZ29zcGFwb21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjE0MjUsImV4cCI6MjA2ODQzNzQyNX0.F8niPjvaLTqNQc-bI3AzCuCRqE3rOcREKQ6rL6GxjtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});